### ISSUE TITLE
loader failing 

### ISSUE THREAD

**Issue by thangarajdeivasikamani** [John1liu/YOLOV5-DeepSORT-Vehicle-Tracking-Master#7]
Hello ,
When I execute the repo I am getting below error.
pls check.

(pytorchwebapi) C:\MachineLearning\Tracking\new\YOLOV5-DeepSORT-Vehicle-Tracking-Master>python track.py --source cut3.avi
Namespace(agnostic_nms=False, augment=False, classes=[0, 1, 2, 3, 4], conf_thres=0.4, config_deepsort='deep_sort_pytorch/configs/deep_sort.yaml', device='', fourcc
='mp4v', img_size=640, iou_thres=0.5, output='inference/output', save_txt=False, source='cut3.avi', view_img=False, weights='yolov5/weights/best.pt')
Traceback (most recent call last):
  File "track.py", line 265, in <module>
    detect(args)
  File "track.py", line 73, in detect
    cfg.merge_from_file(opt.config_deepsort)
  File "C:\MachineLearning\Tracking\new\YOLOV5-DeepSORT-Vehicle-Tracking-Master\deep_sort_pytorch\utils\parser.py", line 24, in merge_from_file
    self.update(yaml.load(fo.read()))
TypeError: load() missing 1 required positional argument: 'Loader'

(pytorchwebapi) C:\MachineLearning\Tracking\new\YOLOV5-DeepSORT-Vehicle-Tracking-Master>

**Comment by kavinteng** [comment]
You can use one of the yaml.full_load() or yaml.safe_load() methods.

**Comment by thangarajdeivasikamani** [comment]
> You can use one of the yaml.full_load() or yaml.safe_load() methods.

**Comment by thangarajdeivasikamani** [comment]
Could you please share exact step where we need to specify the yaml file?  And also location of the specificed ymal  file in the repo. Because i have followed the same steps mentioned in the readme.md file still it's failed.

**Comment by kavinteng** [comment]
on dir "C:\MachineLearning\Tracking\new\YOLOV5-DeepSORT-Vehicle-Tracking-Master\deep_sort_pytorch\utils\parser.py". You will find parser.py with in code line 24 on function merge_from_file that is function use in project. And change it to self.update(yaml.safe_load(fo.read()))
